[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]
  included_files = ["netlify/functions/api-direct.js"]

# API requests go to the function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-direct/:splat"
  status = 200

# All other routes go to the SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Required environment variables for build:
# CLERK_SECRET_KEY
# VITE_CLERK_PUBLISHABLE_KEY
# VITE_SITE_URL 