[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

# API requests go to the function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-direct/:splat"
  status = 200
  force = true

# All other routes go to the SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20" 